### PR TITLE
Change import to support Django 4.0

### PR DESCRIPTION
**Pull request by dryan**
[Django 4.0 removed the ugettext_ family of functions](https://docs.djangoproject.com/en/4.0/releases/4.0/#features-removed-in-4-0) so this import statement needs updating.

### CODE REVIEW

**Review by Giesl — APPROVED** [review]

**Comment by stianjensen** [comment]
You can amend your commit with no changes with `git commit --amend`, and then `git push -f` to force push the branch. That should trigger a new build.

**Review by Giesl — APPROVED** [review]

**Review by Giesl — APPROVED** [review]

**Review by whob13 — APPROVED** [review]

**Comment by whob13** [comment]
Is there a timeline to get this pushed to master? I'd like to update a project to Django 4 but will wait on this if it's coming soon.

**Comment by erdem** [comment]
Hi All,

I couldn't login to my github account for a while because of a sim card issue. I will tackle this along with other PRs in this week. Really sorry for the delay.

**Review by erdem — APPROVED** [review]

**Comment by erdem** [comment]
FYI, I have published the [0.3.3](https://pypi.org/project/django-map-widgets/) release.

```
pip install django-map-widgets==0.3.3
```

**Pull request merged**
