### PR TITLE
fix six imports (support django 3 / drop python 2)

### PR DESCRIPTION
**Pull request by tuky**
lets move on together in this PR :-)

one thing to improve would be to drop the usage of `six` all together.

### CODE REVIEW

**Comment by erdem** [comment]
Thank you for your contribution @tuky. Good to have if we can fix this issue.

I looked at the test failures on this PR today. I fixed python 2 errors but Travis CI environment still has some issues with Postgis. I couldn't fix those issues yet.  

https://github.com/erdem/django-map-widgets/tree/ci_fixes

If you have an idea about fixing the errors on this branch, let me know. Besides that, I'll look into it tomorrow again.  

Thanks

**Comment by erdem** [comment]
Hi @tuky 

I fixed GDAL setup issues on pipeline and pushed the master branch. Could you update your fork repo? 

I can't merge the PR if the pipeline not green. 

Thanks

**Comment by erdem** [comment]
I don't know why but update branch button wasn't available when I pushed my changes to master. I merged the PR and all looks green. ✅

**Comment by tuky** [comment]
great, thx!

**Comment by dryan** [comment]
Any idea when this will get released to PyPi?

**Comment by erdem** [comment]
@dryan not so long, it on my todo list. I'll update the issue topic.

**Comment by erdem** [comment]
https://github.com/erdem/django-map-widgets/issues/104#issuecomment-589894063

**Pull request merged**
