### PR TITLE
Fix jquery loading by using vendored django version

### LINKED ISSUE #100: JQuery Conflict with Django.ModelAdmin.autocomplete_fields
The problem is caused by the use of different jQuery files. Django relies on jquery.js (the one with ajax functions) to work, while map-widgets uses the jquery-3.3.1.slim.min.js (which has ajax stripped away). `autocomplete_fields` will thus stop working.

### PR DESCRIPTION
**Pull request by yakky**
Due to https://docs.djangoproject.com/en/2.2/releases/2.2/#merging-of-form-media-assets the media asset dependencies needs an update.

By depending on vendored jquery version with `jquery.init.js` dependency, we ensure that jquery is initialized correctly on rendering

Fix #100

### CODE REVIEW

**Comment by erdem** [comment]
Thank you for your PR @yakky. 

PostGIS tests are failing on pipeline, TravisCI must be updated something. After fix that problem ASAP, I'll merge your PR. Feel free to contribute to the project!

**Comment by yakky** [comment]
Thanks @erdem 
I have another minor PR in the pipeline, actually :)

**Comment by erdem** [comment]
Hi @yakky 

Sorry for delayed response. Unfournetly, I can't merge this PR at this state because you are importing jquery files from django admin app. Django admin could be disabled in a project and in this case map widgets will not able to work without it. Besides, using django admin jquery is not a best practice if you are implementing any feature to admin. That's why I loaded jquery a different source.

**Comment by yakky** [comment]
@erdem I am open to different solutions
Due to linked changes, simply including external jquery does not work on django 2.2
We might have to implement a custom version of `query.init.js`  to achieve the same goal

**Comment by yakky** [comment]
Fixed in #108

**Comment by erdem** [comment]
Hi @yakky 

As you noticed I fixed the issue last week. Besides, I just published the new version on PyPI. I tested the new package along with individual Django admin widgets and all works fine. 

I would like to do a special thanks for your contribution. Your new contributions are welcome.

**Comment by yakky** [comment]
@erdem thanks for taking care of the issue with a much more comprehensive solution
I just updated on the project and it's :+1: 
I will happily contribute in the future in case I will have something !

**Pull request closed without merging**
